trigger:
- main

variables:
  dockerRegistryServiceConnection: '0edb5a11-5461-46da-89e0-f20d02bed2c8'
  imageRepository: 'todoapp'
  containerRegistry: 'simpleregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/dockerfile'
  tag: '$(Build.BuildId)'
  vmImageName: 'self-hosted'

stages:

# 🔹 Stage 1: Build
- stage: Build
  displayName: Build and Push Image
  jobs:
  - job: Build
    pool:
      name: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and Push Image
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

# 🔹 Stage 2: Deploy
- stage: Deploy
  displayName: Deploy to ACI
  dependsOn: Build   # 👈 important
  condition: succeeded()
  jobs:
  - job: Deploy
    pool:
      name: $(vmImageName)
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure subscription 1 (281d6df1-9dfc-46bb-a0e9-46971c2d4d33)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az container delete --name todoapp --resource-group Devops-RG --yes || true

          USERNAME=$(az acr credential show --name simpleregistry --query "username" -o tsv)
          PASSWORD=$(az acr credential show --name simpleregistry --query "passwords[0].value" -o tsv)

          az container create \
            --name todoapp \
            --resource-group Devops-RG \
            --image $(containerRegistry)/$(imageRepository):$(tag) \
            --registry-login-server $(containerRegistry) \
            --registry-username $USERNAME \
            --registry-password $PASSWORD \
            --dns-name-label aci-demo-bala \
            --ports 80 \
            --os-type Linux \
            --cpu 1 \
            --memory 1.5